<%@ Page Language="C#" MaintainScrollPositionOnPostback="true" MasterPageFile="~/WebSort.Master" AutoEventWireup="true" CodeBehind="Devicemodes.aspx.cs" Inherits="WebSort.DeviceModes" %>

<%@ Register assembly="DevExpress.Web.v10.2, Version=10.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.Web.ASPxTabControl" tagprefix="dx" %>
<%@ Register assembly="DevExpress.Web.v10.2, Version=10.2.3.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.Web.ASPxClasses" tagprefix="dx" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .style16 {
            width: 349px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <script language='javascript'>
        function myPostBack() {
            var o = window.event.srcElement;

            if (o.tagName == "INPUT" && o.type == "checkbox") {
                __doPostBack("", "");
            }
        }

        function confirm_delete(deviceid) {
            var message = "Are you sure you want to delete ";
            message = message.concat(deviceid, "?");

            if (confirm(message) == true)
                return true;
            else
                return false;
        }
    </script>

    <table>
        <tr>
            <td valign="top">
                <asp:UpdatePanel ID="UpdatePanel4" runat="server" UpdateMode="Conditional">
                    <ContentTemplate>
                        <asp:TreeView ID="TreeView2" runat="server" AutoGenerateDataBindings="False"
                            BorderColor="Black" BorderStyle="Solid" BorderWidth="1px"
                            EnableClientScript="true" NodeWrap="True"
                            OnSelectedNodeChanged="TreeView2_SelectedNodeChanged"
                            OnTreeNodeCheckChanged="TreeView2_TreeNodeCheckChanged"
                            OnTreeNodePopulate="TreeView2_TreeNodePopulate" ShowCheckBoxes="Leaf"
                            ShowLines="True" Width="516px">
                            <SelectedNodeStyle BorderColor="Black" BorderStyle="Solid" BorderWidth="1px"
                                Font-Italic="False" Font-Underline="False"
                                HorizontalPadding="2px" NodeSpacing="2px" />
                            <Nodes>
                                <asp:TreeNode Expanded="true" PopulateOnDemand="true" SelectAction="Expand"
                                    Text="Diagnostics" Value="0" />
                            </Nodes>
                            <RootNodeStyle />
                            <NodeStyle HorizontalPadding="2px" NodeSpacing="2px" />
                        </asp:TreeView>
                        <asp:CheckBox ID="CheckBox4" runat="server" Checked="True" />
                        <asp:Label ID="Label7" runat="server"
                            Text="Checkbox activates/deactivates device mode"></asp:Label>
                        <br />
                        <br />
                        <asp:UpdatePanel ID="UpdatePanel10" runat="server" UpdateMode="Conditional">
                            <ContentTemplate>
                                <table style="width: 100%;">
                                    <tr>
                                        <td class="style15">
                                            <asp:Label ID="Label8" runat="server" Font-Bold="True"
                                                Text="Additional Mode Data:"></asp:Label>
                                        </td>
                                        <td class="style1">
                                            <asp:TextBox ID="TextBoxParameter0" runat="server"></asp:TextBox>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="style15">
                                            <asp:Label ID="Label22" runat="server" Font-Bold="True"
                                                Text="Description:"></asp:Label>
                                        </td>
                                        <td class="style1">
                                            <asp:TextBox ID="TextBoxParameterDescription0" runat="server"
                                                BackColor="#A4A4A4" Width="350px"></asp:TextBox>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="style15">&nbsp;</td>
                                        <td class="style1">
                                            <asp:Button ID="ButtonSave4" runat="server" OnClick="ButtonSave4_Click" Text="Save"
                                                CssClass="btn-raptor" />
                                        </td>
                                    </tr>
                                </table>
                            </ContentTemplate>
                        </asp:UpdatePanel>
                        </td>
                    </ContentTemplate>
                </asp:UpdatePanel>
            </td>
        </tr>
        <tr>
            <td>
                <asp:UpdatePanel runat="server" UpdateMode="Conditional" ID="UpdatePanel9">
                    <ContentTemplate>
                        <asp:Button ID="ButtonAddNewMode0" runat="server" CausesValidation="False"
                            OnClick="ButtonAddNewMode0_Click" Text="Add New Mode" CssClass="btn-raptor" />
                        <asp:Button ID="ButtonRenameItem0" runat="server" CausesValidation="False"
                            OnClick="ButtonRenameItem0_Click" Text="Rename Mode" CssClass="btn-raptor" />
                        <asp:Button ID="ButtonDeleteItem0" runat="server" CausesValidation="False"
                            OnClick="ButtonDeleteItem0_Click" Text="Delete Mode" CssClass="btn-raptor"/>
                        <asp:Button ID="ButtonChangeItemID0" runat="server" CausesValidation="False"
                            OnClick="ButtonChangeItemID0_Click" Text="Change Mode ID" CssClass="btn-raptor" />
                        <br />
                        <br />
                        <asp:Label ID="LabelOldName2" runat="server"
                            Text="Old Mode Name: " Visible="False"></asp:Label>
                        <asp:Label ID="LabelOldName3" runat="server"
                            Visible="False"></asp:Label>
                        <asp:Label ID="LabelOldItemID2" runat="server"
                            Text="Old Mode ID: " Visible="False"></asp:Label>
                        <asp:Label ID="LabelOldItemID3" runat="server"
                            Visible="False"></asp:Label>
                        <br />
                        <asp:Label ID="LabelNewName0" runat="server"
                            Text="New Mode Name: " Visible="False"></asp:Label>
                        <asp:TextBox ID="TextBoxNewName0" runat="server"
                            OnTextChanged="TextBoxNewName_TextChanged" Visible="False" Width="200px"></asp:TextBox>
                        <asp:Label ID="LabelNewItemID0" runat="server"
                            Text="New Mode ID: " Visible="False"></asp:Label>
                        <asp:DropDownList ID="DropDownListItemID0" runat="server" Visible="False">
                        </asp:DropDownList>
                        <br />

                        <asp:Button ID="ButtonSave2" runat="server" OnClick="ButtonSave2_Click"
                            Text="Save" Visible="False" CssClass="btn-raptor" />
                        <asp:Button ID="ButtonCancel2" runat="server" OnClick="ButtonCancel2_Click"
                            Text="Cancel" Visible="False" CssClass="btn-raptor" />
                        <asp:Button ID="ButtonSave3" runat="server" OnClick="ButtonSave3_Click"
                            Text="Save" Visible="False" CssClass="btn-raptor" />
                        <asp:Button ID="ButtonCancel3" runat="server" OnClick="ButtonCancel3_Click"
                            Text="Cancel" Visible="False" CssClass="btn-raptor" />

                    </ContentTemplate>
                </asp:UpdatePanel>

            </td>
        </tr>
        <tr>
            <td></td>
        </tr>
    </table>
    <dx:ASPxPageControl ID="ASPxPageControl1" runat="server"
        ActiveTabIndex="1"
        CssFilePath="~/App_Themes/BlackGlass/{0}/styles.css"
        CssPostfix="BlackGlass"
        SaveStateToCookies="True"
        Width="922px" Visible="false">
        <TabPages>
            <dx:TabPage Text="Diagnostic Modes" Visible="False">
                <ContentCollection>
                    <dx:ContentControl ID="ContentControl1" runat="server">
                        <table>
                            <tr>
                                <td valign="top">

                                    <asp:UpdatePanel ID="UpdatePanel6" runat="server"
                                        UpdateMode="Conditional">
                                        <ContentTemplate>
                                            <asp:TreeView ID="TreeView1" runat="server"
                                                AutoGenerateDataBindings="False"
                                                BorderColor="Black"
                                                BorderStyle="Solid"
                                                BorderWidth="1px"
                                                EnableClientScript="true"
                                                NodeWrap="True"
                                                OnSelectedNodeChanged="TreeView1_SelectedNodeChanged"
                                                OnTreeNodeCheckChanged="TreeView1_TreeNodeCheckChanged"
                                                OnTreeNodePopulate="TreeView1_TreeNodePopulate"
                                                ShowCheckBoxes="Leaf"
                                                ShowLines="True" Width="332px">
                                                <SelectedNodeStyle BorderColor="Black" BorderStyle="Solid" BorderWidth="1px"
                                                    HorizontalPadding="2px" NodeSpacing="2px" />
                                                <Nodes>
                                                    <asp:TreeNode Expanded="true" PopulateOnDemand="true" SelectAction="Expand"
                                                        Text="Diagnostics" Value="0" />
                                                </Nodes>
                                                <RootNodeStyle />
                                                <NodeStyle HorizontalPadding="2px" NodeSpacing="2px" />
                                            </asp:TreeView>

                                            <asp:CheckBox ID="CheckBox1" runat="server" Checked="True" />
                                            <asp:Label ID="Label1" runat="server"
                                                Text="Checkbox activates/deactivates device test"></asp:Label>
                                            <br />
                                            &nbsp;<br />
                                            <asp:UpdatePanel ID="UpdatePanel7" runat="server" UpdateMode="Conditional">
                                                <ContentTemplate>
                                                    <table style="width: 100%;">
                                                        <tr>
                                                            <td class="style14">
                                                                <asp:Label ID="Label2" runat="server" Font-Bold="True"
                                                                    Text="Additional Test Data:"></asp:Label>
                                                            </td>
                                                            <td class="style16">
                                                                <asp:TextBox ID="TextBoxParameter" runat="server"></asp:TextBox>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td class="style14">
                                                                <asp:Label ID="Label21" runat="server" Font-Bold="True"
                                                                    Text="Description:"></asp:Label>
                                                            </td>
                                                            <td class="style16">
                                                                <asp:TextBox ID="TextBoxParameterDescription" runat="server"
                                                                    BackColor="#A4A4A4"
                                                                    Width="350px"></asp:TextBox>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td class="style14">&nbsp;</td>
                                                            <td class="style16">
                                                                <asp:Button ID="ButtonSave1" runat="server" OnClick="ButtonSave1_Click"
                                                                    Text="Save" CssClass="btn-raptor" />
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </ContentTemplate>
                                            </asp:UpdatePanel>
                                        </ContentTemplate>
                                        <Triggers>
                                            <asp:AsyncPostBackTrigger ControlID="TreeView1"
                                                EventName="TreeNodeCheckChanged" />
                                            <asp:AsyncPostBackTrigger ControlID="TreeView1"
                                                EventName="SelectedNodeChanged" />
                                        </Triggers>
                                    </asp:UpdatePanel>

                                </td>

                                <td valign="top">
                                    <asp:UpdatePanel ID="UpdatePanel11" runat="server" UpdateMode="Conditional">
                                        <ContentTemplate>
                                            <asp:Label ID="Labelenc" runat="server" BackColor="White" BorderStyle="Solid"
                                                Font-Bold="True" Font-Names="Arial Black" Font-Size="96px" Visible="False"></asp:Label>
                                            <asp:Timer ID="Timer3" runat="server" Enabled="False" Interval="250"
                                                OnTick="Timer3_Tick">
                                            </asp:Timer>
                                        </ContentTemplate>
                                        <Triggers>
                                            <asp:AsyncPostBackTrigger ControlID="TreeView1"
                                                EventName="TreeNodeCheckChanged" />
                                            <asp:AsyncPostBackTrigger ControlID="Timer3" EventName="Tick" />
                                        </Triggers>
                                    </asp:UpdatePanel>
                                </td>

                            </tr>
                            <tr>
                                <td colspan="2" class="style5">
                                    <asp:UpdatePanel ID="UpdatePanel8" runat="server" UpdateMode="Conditional">
                                        <ContentTemplate>




                                            <asp:Button runat="server" CausesValidation="False"
                                                Text="Add New Test" CssClass="btn-raptor" ID="ButtonAddNewTest"
                                                OnClick="ButtonAddNewTest_Click"></asp:Button>

                                            <asp:Button runat="server" CausesValidation="False"
                                                Text="Rename Test" CssClass="btn-raptor" ID="ButtonRenameItem"
                                                OnClick="ButtonRenameItem_Click"></asp:Button>

                                            <asp:Button runat="server" CausesValidation="False"
                                                Text="Delete Test" CssClass="btn-raptor" ID="ButtonDeleteItem"
                                                OnClick="ButtonDeleteItem_Click"></asp:Button>

                                            <asp:Button runat="server" CausesValidation="False"
                                                Text="Change Test ID" CssClass="btn-raptor" ID="ButtonChangeItemID"
                                                OnClick="ButtonChangeItemID_Click"></asp:Button>
                                            <br />

                                            <br />

                                            <asp:Label runat="server"
                                                Text="Old Test Name: " ID="LabelOldName"
                                                Visible="False"></asp:Label>

                                            <asp:Label runat="server"
                                                ID="LabelOldName1" Visible="False"></asp:Label>

                                            <asp:Label runat="server" Text="Old Test ID: "
                                                ID="LabelOldItemID" Visible="False"></asp:Label>

                                            <asp:Label runat="server"
                                                ID="LabelOldItemID1" Visible="False"></asp:Label>

                                            <br />
                                            <asp:Label runat="server"
                                                Text="New Test Name: " ID="LabelNewName"
                                                Visible="False"></asp:Label>

                                            <asp:TextBox runat="server" Width="200px"
                                                ID="TextBoxNewName" Visible="False" OnTextChanged="TextBoxNewName_TextChanged"></asp:TextBox>

                                            <asp:Label runat="server" Text="New Test ID: "
                                                ID="LabelNewItemID" Visible="False"></asp:Label>

                                            <asp:DropDownList runat="server"
                                                ID="DropDownListItemID" Visible="False">
                                            </asp:DropDownList>

                                            <br />
                                            <asp:Button runat="server" Text="Save"
                                                CssClass="btn-raptor" ID="ButtonSave" Visible="False" OnClick="ButtonSave_Click"></asp:Button>

                                            <asp:Button runat="server" Text="Cancel"
                                                CssClass="btn-raptor" ID="ButtonCancel" Visible="False" OnClick="ButtonCancel_Click"></asp:Button>

                                            <asp:Button runat="server" Text="Save"
                                                CssClass="btn-raptor" ID="ButtonSave0" Visible="False" OnClick="ButtonSave0_Click"></asp:Button>

                                            <asp:Button runat="server" Text="Cancel"
                                                CssClass="btn-raptor" ID="ButtonCancel0" Visible="False" OnClick="ButtonCancel0_Click"></asp:Button>

                                            </td>
                                        </ContentTemplate>
                                    </asp:UpdatePanel>
                            </tr>

                            <tr>
                                <td colspan="2"></td>
                            </tr>
                        </table>
                    </dx:ContentControl>
                </ContentCollection>
            </dx:TabPage>
            <dx:TabPage Text="Diagnostic Modes">
                <ContentCollection>
                    <dx:ContentControl ID="ContentControl2" runat="server">
                    </dx:ContentControl>
                </ContentCollection>
            </dx:TabPage>
        </TabPages>
    </dx:ASPxPageControl>
    <asp:UpdatePanel ID="UpdatePanel5" runat="server">
        <ContentTemplate>
            <asp:Button ID="ButtonRefreshAll" runat="server" CssClass="btn-raptor"
                OnClick="ButtonRefreshAll_Click" Text="Refresh All" Visible="False" />
            <asp:Label ID="LabelTimeout" runat="server" ForeColor="Red"
                Text="Timeout Communicating with PLC" Visible="False"></asp:Label>
            <asp:UpdateProgress ID="UpdateProgress1" runat="server"
                AssociatedUpdatePanelID="UpdatePanel5">
                <ProgressTemplate>
                    Reading Diagnostic Status, Please Wait...

                </ProgressTemplate>
            </asp:UpdateProgress>
        </ContentTemplate>
    </asp:UpdatePanel>
    <asp:Timer ID="Timer2" runat="server" Interval="10000" OnTick="Timer2_Tick"
        Enabled="False">
    </asp:Timer>

</asp:Content>